apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  labels:
    name: rabbitmqtt
data:
  enabled_plugins: |
    [rabbitmq_federation,rabbitmq_management,rabbitmq_peer_discovery_k8s,rabbitmq_mqtt,rabbitmq_shovel,rabbitmq_shovel_management,rabbitmq_prometheus].
  rabbitmq.conf: |
    loopback_users.guest = false
    listeners.tcp.default = 5672
    management.tcp.port = 15672
    mqtt.listeners.tcp.default = 1883
    mqtt.default_user = guest
    mqtt.default_pass = guest
    mqtt.allow_anonymous = true
    mqtt.vhost = /
    mqtt.exchange = amq.topic
    mqtt.subscription_ttl = 86400000
    mqtt.prefetch = 10
    mqtt.retained_message_store = rabbit_mqtt_retained_msg_store_ets
    cluster_formation.peer_discovery_backend  = rabbit_peer_discovery_k8s
    cluster_formation.k8s.host = kubernetes.default.svc.cluster.local
    cluster_formation.k8s.address_type = hostname
    cluster_formation.node_cleanup.only_log_warning = true
    vm_memory_high_watermark.absolute = 2147483648
    log.file.rotation.size = 5368709120