apiVersion: v1
kind: Secret
metadata:
  name: rabbit-secret
  labels:
    name: rabbitmqtt
  namespace: rabbits
type: Opaque
data:
  # echo -n "cookie-value" | base64
  RABBITMQ_ERLANG_COOKIE: V0lXVkhDRFRDSVVBV0FOTE1RQVc=